Repository garden-share-08/garden-share-be, pull requests merged in 2021-02, with the labels that each got.

#18 Produce
  app/graphql/queries/fetch_all_produce.rb
  app/graphql/queries/fetch_produce_by_name.rb
  app/graphql/types/produce_type.rb
  app/graphql/types/query_type.rb
  app/models/produce.rb
  db/migrate/20210220205521_create_produces.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/produces.rb
  spec/models/produce_spec.rb
  spec/requests/delete_listing_spec.rb
  spec/requests/edit_listing_spec.rb
  spec/requests/queries/query_produce_spec.rb
Labels: BE, MVP

#22 Listings
  app/graphql/queries/get_user_listings.rb
  spec/requests/queries/get_listings_spec.rb
  spec/requests/queries/get_user_listings_spec.rb
Labels: BE

#30 Offers
  app/graphql/queries/get_user_offers.rb
  app/graphql/types/offer_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/user_type.rb
  spec/factories/listings.rb
  spec/requests/queries/get_user_offers_spec.rb
Labels: BE, MVP

#32 Listings
  app/graphql/mutations/delete_offer.rb
  app/graphql/queries/get_listing_status.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  spec/requests/mutations/delete_offer_spec.rb
  spec/requests/queries/get_listing_status_spec.rb
Labels: BE, MVP

#33 Accept offer
  app/graphql/mutations/accept_offer.rb
  app/graphql/mutations/decline_offer.rb
  app/graphql/types/mutation_type.rb
  spec/requests/mutations/accept_offer_spec.rb
  spec/requests/mutations/decline_offer_spec.rb
Labels: BE, MVP

#35 Accepted offer
  app/graphql/mutations/create_user.rb
  spec/requests/mutations/accept_offer_spec.rb
  spec/requests/mutations/create_user_spec.rb
Labels: BE, MVP, bug

#38 Add users and listings to seeds file
  db/seeds.rb
Labels: BE, MVP

#40 Location service
  .gitignore
  Gemfile
  Gemfile.lock
  app/graphql/queries/get_listings.rb
  app/services/location_service.rb
  spec/fixtures/get_zip_codes.json
  spec/rails_helper.rb
  spec/requests/queries/get_listings_spec.rb
  spec/services/location_service_spec.rb
Labels: BE, MVP

#42 Chris readme
  .travis.yml
  Gemfile.lock
  README.md
Labels: BE, MVP
